### ISSUE TITLE
How to run the teamspark step by step?

### ISSUE THREAD

**Issue by caiqinghua** [tyrchen/teamspark#1]
In the readme, there are only two steps: install monbodb and meteor; configuration.
But if do the both. It don't work well. It will occur error: AuditTrails undefined. If i delete the AuditTrails in the access_control.coffee, other error will be coming.

Could you issue a instruction that can let user use the teamspark step by step?

**Comment by tyrchen** [comment]
This is caused by the recent upgrade of meteorjs suite. The version when I develop teamspark is 0.5.x, now it is 0.6.x. I'll try to fix this problem soon.

**Comment by tyrchen** [comment]
Now the code has been migrated with the latest meteor. And I've made the demo (http://ts-demo.tchen.me) work correctly. Please try again.
