### ISSUE TITLE
Online demo can't work.

### ISSUE THREAD

**Issue by caiqinghua** [tyrchen/teamspark#2]
http://ts-demo.tchen.me. it cant work.

**Comment by tyrchen** [comment]
The demo service has been stopped carelessly.

**Comment by tyrchen** [comment]
fixed.

**Comment by booxood** [comment]
@tyrchen 

again stopped...

> It works!
> 
> This is the default web page for this server.
> 
> The web server software is running but no content has been added, yet.

**Comment by tyrchen** [comment]
Try http://teamspark.meteor.com I updated document.

**Comment by booxood** [comment]
ok, it's working.  great work !
